// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8NzvVGUqwIoT3fdRLwkhmv3YnOsQoRY0',
    appId: '1:269525143257:web:05a63b26e8e86e2c3838c8',
    messagingSenderId: '269525143257',
    projectId: 'reservacanchas-338bf',
    authDomain: 'reservacanchas-338bf.firebaseapp.com',
    storageBucket: 'reservacanchas-338bf.firebasestorage.app',
    measurementId: 'G-BZ7VLE547P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO7Bwvs3zochBiQGUEb3Oh6ymLqmHFQMM',
    appId: '1:269525143257:android:8d611a886798eb843838c8',
    messagingSenderId: '269525143257',
    projectId: 'reservacanchas-338bf',
    storageBucket: 'reservacanchas-338bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX4pu_TEFWwCmOu7Hnwe1i3Jg8g6PZ_ok',
    appId: '1:269525143257:ios:5b1761c86fec420c3838c8',
    messagingSenderId: '269525143257',
    projectId: 'reservacanchas-338bf',
    storageBucket: 'reservacanchas-338bf.firebasestorage.app',
    iosBundleId: 'com.example.resrevacionCanchas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX4pu_TEFWwCmOu7Hnwe1i3Jg8g6PZ_ok',
    appId: '1:269525143257:ios:5b1761c86fec420c3838c8',
    messagingSenderId: '269525143257',
    projectId: 'reservacanchas-338bf',
    storageBucket: 'reservacanchas-338bf.firebasestorage.app',
    iosBundleId: 'com.example.resrevacionCanchas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8NzvVGUqwIoT3fdRLwkhmv3YnOsQoRY0',
    appId: '1:269525143257:web:92d1bd3f03d976a73838c8',
    messagingSenderId: '269525143257',
    projectId: 'reservacanchas-338bf',
    authDomain: 'reservacanchas-338bf.firebaseapp.com',
    storageBucket: 'reservacanchas-338bf.firebasestorage.app',
    measurementId: 'G-HTNNNB0E5G',
  );
}
